version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - doxygen=1.9.4-4

sphinx:
  configuration: docs/source/conf.py
  builder: "html"

python:
  install:
    - requirements: docs/requirements.txt