name: Publish Release
on:
  create:

concurrency:
  group: publish-release-${{ github.workflow }}-${{ github.ref }}

jobs:
  publish-conan-branch-package:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    uses: dice-group/cpp-conan-release-reusable-workflow/.github/workflows/publish-release.yml@main
    with:
      public_artifactory: true
      os: ubuntu-22.04
      compiler: clang-17
      cmake-version: 3.24.0
      conan-version: 2.3.0
      use-tag: true
      conan-options: -o boost/*:header_only=True
    secrets:
      CONAN_USER: ${{ secrets.CONAN_USER }}
      CONAN_PW: ${{ secrets.CONAN_PW }}
