on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      cmake-version:
        required: true
        type:
          string
      compiler:
        required: true
        type: string

jobs:
  build-and-test-conan-package:
    name: Build and test conan package
    runs-on: ${{ inputs.os }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Add Repos for for gcc-13 and clang-16
        run: |
          # gcc-13
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y

          # clang-16
          source /etc/os-release
          echo "deb http://apt.llvm.org/${UBUNTU_CODENAME}/ llvm-toolchain-${UBUNTU_CODENAME}-16 main" | sudo tee /etc/apt/sources.list.d/llvm-16.list
          curl https://apt.llvm.org/llvm-snapshot.gpg.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/llvm-16.gpg > /dev/null

          sudo apt-get update -y

      - name: Get minimum cmake version
        uses: lukka/get-cmake@v3.24.3
        with:
          cmakeVersion: ${{ inputs.cmake-version }}

      - name: Install compiler
        id: install_cc
        uses: rlalik/setup-cpp-compiler@v1.2
        with:
          compiler: ${{  inputs.compiler }}

      - name: use mold as default linker
        uses: rui314/setup-mold@v1

      - name: Configure conan
        run: |
          pip3 install "conan==1.60.1"
          conan user
          conan profile new --detect default
          conan profile update settings.compiler.libcxx=libstdc++11 default
          conan remote add -f dice-group https://conan.dice-research.org/artifactory/api/conan/tentris

      - name: Cache conan data
        id: cache-conan
        uses: actions/cache@v3
        with:
          path: ~/.conan/data
          key: ${{ inputs.os }}-${{ inputs.compiler }}-conan

      - name: Check out sources
        uses: actions/checkout@v3

      - name: Test conan package
        env:
          CC: ${{ steps.install_cc.outputs.cc }}
          CXX: ${{ steps.install_cc.outputs.cxx }}
        run: |
          # build and test package
          conan create . $(conan inspect . --raw name)/$(conan inspect . --raw version)@ci/testing -pr:b=default --build missing
          conan remove -f $(conan inspect . --raw name)/$(conan inspect . --raw version)@ci/testing

  test-fetch-content-static:
    name: Test cmake FetchContent (static lib)
    uses: ./.github/workflows/reusable_fetch_content.yml
    with:
      os: ${{ inputs.os }}
      compiler: ${{ inputs.compiler }}
      cmake-version: ${{ inputs.cmake-version }}
      build-shared-libs: false

  test-fetch-content-shared:
    name: Test cmake FetchContent (shared lib)
    uses: ./.github/workflows/reusable_fetch_content.yml
    with:
      os: ${{ inputs.os }}
      compiler: ${{ inputs.compiler }}
      cmake-version: ${{ inputs.cmake-version }}
      build-shared-libs: true
