name: Run unit tests and examples
on: [ 'pull_request' ]
jobs:
  tests_and_example_matrix:
    strategy:
      matrix:
        cppenv:
          - os: ubuntu-22.04
            compiler: gcc-13
          - os: ubuntu-24.04-arm
            compiler: gcc-13

          - os: ubuntu-22.04
            compiler: clang-17
          - os: ubuntu-22.04
            compiler: clang-18
          - os: ubuntu-22.04
            compiler: clang-19
          - os: ubuntu-24.04-arm
            compiler: clang-19

      fail-fast: false
    name: ${{ matrix.cppenv.compiler }}, ${{ matrix.cppenv.os }}
    uses: ./.github/workflows/reusable_run_test_and_examples.yml
    with:
      os: ${{ matrix.cppenv.os }}
      compiler: ${{ matrix.cppenv.compiler }}
      cmake-version: 3.24.0
      with-coverage: false
      with-sanitizer: ${{ matrix.cppenv.compiler == 'clang-17' }}
      with-AVX: ${{ matrix.cppenv.compiler == 'clang-17' }}
