name: Run unit tests and examples
on: [ 'pull_request' ]


jobs:
  tests_and_example_matrix:
    strategy:
      matrix:
        cppenv:
          - os: ubuntu-22.04
            compiler: gcc-13
      fail-fast: false
    name: ${{ matrix.cppenv.compiler }}, ${{ matrix.cppenv.os }}
    uses: ./.github/workflows/reusable_run_test_and_examples_by_linking_type.yml
    with:
      os: ${{ matrix.cppenv.os }}
      compiler: ${{ matrix.cppenv.compiler }}
      cmake-version: 3.24.0
      with-coverage: true
      with-sanitizer: false
      build-shared-libs: true
    secrets:
      coverall-token: ${{ secrets.COVERALLS_TOKEN }}
