name: Packaging and deployment tests
on: [ 'pull_request' ]


jobs:
  packaging:
    name: Packaging and deployment tests
    uses: ./.github/workflows/reusable_packaging_and_deployment.yml
    with:
      os: ubuntu-22.04
      compiler: clang-14
      cmake-version: 3.22.6
